In [1]:
import pandas as pd 
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
final = pd.read_csv("final.csv")
final

,Category,Resume,Skill,Experience(months)
0,Data Science,Skills * Programming Languages: Python (pandas...,"['Pandas', 'Numpy', 'Scipy', 'SCikit-learn', '...",24
1,Data Science,Skills R Python SAP HANA Tableau SAP HANA...,"['R', 'Python', 'SAP HANA', 'Tableau', 'SAP HA...",12
2,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...,"['Python', 'Machine learning', 'Sklearn', 'Sci...",12
3,Data Science,Education Details \r\n B.Tech Rayat and Bahr...,"['Software Development: inception, requirement...",24
4,Data Science,Skills * Programming Languages: Python (pandas...,"['Programming Languages: Python, Java', 'Datab...",24
...,...,...,...,...
157,Testing,COMPUTER PROFICIENCY Basic: MS-Office (Power...,"['MS Office', 'CPP', 'Android Developer', 'Man...",12
158,Testing,Computer Skills: Proficient in MS office (Wo...,"['Windows', 'MS Office', 'Insulation Resistanc...",6
159,Testing,Willingness to accept the challenges. Positi...,"['C', 'Windows 7-8/NT/XP', 'C++', 'Documentati...",9
160,Testing,COMPUTER SKILLS & SOFTWARE KNOWLEDGE MS-Power ...,"['MS Office', 'C', 'Portius (PCB Design)', 'Mu...",6
161,Testing,Skill Set OS Windows XP/7/8/8.1/10 Database MY...,"['Windows XP/7/8/8.1/10', 'MySQL', 'Html', 'SQ...",24

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

# Assuming you have a list of resumes and skills
final = pd.read_csv('final.csv')

resumes = final['Resume'].tolist()
skills = final['Skill'].tolist()
categories = final['Category'].tolist()
experience = final['Experience(months)'].tolist()

# User inputs
user_category = input("Enter your category/job title: ").lower()
user_experience = int(input("Enter your total experience in months: "))
user_skills = input("Enter your skills : ").strip('[]').split(',')

# Filter data based on user input
filtered_data = final[(final['Category'].str.lower() == user_category) & (final['Experience(months)'] <= user_experience)]

print(f"filtered data : {filtered_data}")
print("\n")

if filtered_data.empty:
    print(f"No matching resumes found for the category '{user_category}' and experience '{user_experience}' months.")
    exit()

# Separate filtered resumes for training
filtered_resumes = filtered_data['Resume'].tolist()
filtered_labels = list(range(len(filtered_data)))

# Combine user details with existing skills for training
user_details = f"{user_category}, {', '.join(user_skills)}, {user_experience}"
all_data = filtered_resumes + [user_details]

# Convert text data to TF-IDF features
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(all_data)

# Train the model only on the filtered data
model = MultinomialNB()
model.fit(X[:-1], filtered_labels)  # Exclude the user details for training

# User details to predict skills
user_data = vectorizer.transform([user_details])

# Predict skills for user details
predicted_labels = model.predict(user_data)

# Get the corresponding skills based on predicted labels
filtered_predicted_skills = [filtered_data.iloc[i]['Skill'] for i in predicted_labels]

# Provide recommendations
if filtered_predicted_skills:
    print("Recommended Skills: ", filtered_predicted_skills)
else:
    print("Pass your skills. No matching skills found for the given category and experience.")

Enter your category/job title: HR
Enter your total experience in months: 12
Enter your skills : communication, ATS
filtered data :    Category                                             Resume  \
9        HR  TECHNICAL SKILLS  Typeriting  TORA  SPSSEducat...
10       HR  I.T. Skills  indos XP, Ms Office (ord, Excel: ...
11       HR  KEY SKILLS:  Computerized accounting ith tally...
12       HR  Training in Special Education (Certificate Cou...
13       HR  Computer Knoledge:  Proficient in basic use of...
14       HR  SOFTARE SKILLS:  General Computer Proficiency ...

                                                Skill  Experience(months)
9   ['Communication', 'Finance', 'Typewriting', 'T...                   8
10  ['Interactive', 'indos XP', 'Ms Office (word, ...                  11
11  ['Scrum', 'web programming', 'tally', 'Account...                   6
12  ['Counsellor', 'Organizational Behaviour', 'Tr...                   3
13  ['Engineering', 'Administration', ' MS office'...                   6
14  ['Computer science', 'Java', 'Engineering', 'P...                   6


Recommended Skills:  ["['Computer science', 'Java', 'Engineering', 'Programming', 'C', 'C++', 'Database', 'Matlab', 'Communication']"]

In [4]:
# import pandas as pd
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.naive_bayes import MultinomialNB

# # Assuming you have a list of resumes and skills
# final = pd.read_csv('final.csv')

# resumes = final['Resume'].tolist()
# skills = final['Skill'].tolist()
# categories = final['Category'].tolist()
# experience = final['Experience(months)'].tolist()

# # User inputs
# user_category = input("Enter your category/job title: ")
# user_experience = int(input("Enter your total experience in months: "))
# user_skills = input("Enter your skills : ").strip('[]').split(',')

# # Filter data based on user input
# filtered_data = final[(final['Category'] == user_category) & (final['Experience(months)'] <= user_experience)]

# print(f"filtered data : {filtered_data}")
# print("\n")

# if filtered_data.empty:
#     print(f"No matching resumes found for the category '{user_category}' and experience '{user_experience}' months.")
#     exit()

# # Extract all skills from filtered data
# all_filtered_skills = [skill.strip(" '[]") for skills_list in filtered_data['Skill'] for skill in skills_list.split(',')]

# # Convert filtered skills to a set to get unique skills
# recommended_skills = set(all_filtered_skills)

# # Provide recommendations
# if recommended_skills:
#     print("Recommended Skills: ", list(recommended_skills))
# else:
#     print("Pass your skills. No matching skills found for the given category and experience.")